### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by huliz** [euqip/meteor-kitchen-myapp#1]
Hi,
When running "meteor-kitchen myapp.json ../../examples/myapp"
I get this warning: 
File not found "/home/ubuntu/examples/myapp/addons/my_login.html".

The app doesn''t really start
=> Your application has errors. Waiting for file change.

There is no "addons" folder on your repo.

files/entity.json is missing too 

```
                            "source": "files/entity.json",
                            "dest": "PRIVATE_DIR/entity.json"
```

Cheers

**Comment by euqip** [comment]
Hi Hullz,
I added the missing files.  Hope it will work now.
This repository was a middle to keep a working step in my meteor and meteor-kitchen discovery with the use of tap:i18n to translate the content.
Keep me updated!

**Comment by huliz** [comment]
Hi Euqip,
Everything is generating fine now. The app is running as well. I like your idea about generating some initial data and users. I am looking forward seeing updates on this one. 
Thanks for the fix!

**Comment by euqip** [comment]
Hi Hullz,
Thanks for the feedback.
I just added a partial french i18n translation file.  It is used in the templates placed in addons.
To add more language, just copy and change the values in json.  Translations should be accessible to both client and server.

**Comment by huliz** [comment]
It works :+1: 
your example really helps me
